#!/bin/bash

# Switch to proper directory via cd.
cd "$(git rev-parse --show-toplevel)"

# Try to compile the project.
npm run build
BUILD_EXIT="$?"

if [[ "${BUILD_EXIT}" == 0 ]]; then
  printf "\n\033[42m PASS \033[0m Successfully built with no problems. Continuing..."
else
  printf "\n\033[41m FAIL \033[0m Fix project errors and try again."
  exit 1
fi

exit $BUILD_EXIT
